/// Firebase configuration options for the ALPACA app.
///
/// Generated by FlutterFire CLI for project alpaca-mobile-2026.
library;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  /// Firebase options for the Web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT92bsuswPrK4HF61PYEqZ243KX3E89Qc',
    appId: '1:425595420007:web:d05af689c08207e2bb83c2',
    messagingSenderId: '425595420007',
    projectId: 'alpaca-mobile-2026',
    authDomain: 'alpaca-mobile-2026.firebaseapp.com',
    storageBucket: 'alpaca-mobile-2026.firebasestorage.app',
  );

  /// Firebase options for the Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7KtfMLZcI_eRgyEByvmpCAOToLmC8MsE',
    appId: '1:425595420007:android:5a5a2e757083790dbb83c2',
    messagingSenderId: '425595420007',
    projectId: 'alpaca-mobile-2026',
    storageBucket: 'alpaca-mobile-2026.firebasestorage.app',
  );

  /// Firebase options for the iOS platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNY3alblCG-2I5zU_rhFyi-t7lXU9PXlU',
    appId: '1:425595420007:ios:562831f175db56edbb83c2',
    messagingSenderId: '425595420007',
    projectId: 'alpaca-mobile-2026',
    storageBucket: 'alpaca-mobile-2026.firebasestorage.app',
    iosBundleId: 'com.example.alpacaMobile',
  );

  /// Firebase options for the macOS platform (shares iOS config).
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNY3alblCG-2I5zU_rhFyi-t7lXU9PXlU',
    appId: '1:425595420007:ios:562831f175db56edbb83c2',
    messagingSenderId: '425595420007',
    projectId: 'alpaca-mobile-2026',
    storageBucket: 'alpaca-mobile-2026.firebasestorage.app',
    iosBundleId: 'com.example.alpacaMobile',
  );

  /// Firebase options for the Windows platform.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT92bsuswPrK4HF61PYEqZ243KX3E89Qc',
    appId: '1:425595420007:web:e9cb99ed6d17e179bb83c2',
    messagingSenderId: '425595420007',
    projectId: 'alpaca-mobile-2026',
    authDomain: 'alpaca-mobile-2026.firebaseapp.com',
    storageBucket: 'alpaca-mobile-2026.firebasestorage.app',
  );
}
